export const CHANGE_IS_MOBILE = 'CHANGE_IS_MOBILE';
export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';

export const REQUEST_JOKES = 'REQUEST_JOKES';
export const RECEIVE_JOKES = 'RECEIVE_JOKES';
export const NET_ERROR = 'NET_ERROR';
